name: CI/CD Pipeline  

on:  
  push:  
    branches:  
      - development  

jobs:  
  build:  
    runs-on: ubuntu-latest  

    steps:  
      - name: Checkout Repository  
        uses: actions/checkout@v2  

      - name: Install Dependencies (Backend)  
        run: |  
          cd server  
          npm install  

      - name: Install Dependencies (Frontend)  
        run: |  
          cd client  
          npm install  
          npm run build  
